# Generated by Django 6.0.6 on 2026-06-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlshort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name': 'urlshort',
                'verbose_name_plural': 'urlshorts',
                'db_table': 'urlshort',
            },
        ),
    ]
