# Generated by Django 6.0.6 on 2026-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
